steps:
  install:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npm run lint
  dependency-lint:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npx ember dependency-lint
    failure: ignore
  test:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npm run test:ember
    failure: ignore
when:
  - event: pull_request
